spring:
  profiles.active: development

---

spring:
  application:
   name: bp-wallet-server
  datasource:
    url: jdbc:h2:mem:sampletest;MODE=MySQL
    username: root
    password: mypassword
    driverClassName: org.h2.Driver
    hikari:
      idleTimeout: 30000
      connectionTimeout: 180000
      maxLifetime: 1800000
      pool-name: bpServerH2ConnectionPool
      auto-commit: false
      
  h2:
    console:
      enabled: true
      path: /h2
---

spring:
  profiles: development
  application:
   name: bp-wallet-server
  datasource:
   url: jdbc:mysql://localhost:3306/sys?useSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   hikari:
    idle-timeout: 1000
    maximum-pool-size: 10
    minimum-idle: 1
    idleTimeout: 3000
    connectionTimeout: 30000
    maxLifetime: 1800000
    pool-name: bpServerMYSQLConnectionPool
    auto-commit: false
  jpa:
   hibernate.ddl-auto: update
   generate-ddl: true
   show-sql: true
   properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
server:
  port: 0