server:
  port: 8080
spring:
  application:
    name: bp-wallet-client
    
grpc:
  client:
    bp-wallet-server:
      host:
        - 127.0.0.1
      port:
        - 9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true